### PR TITLE
Fix #161 user select in workflows removed selected values

### LINKED ISSUE #161: User selection in workflows form doesn't show selected values.
### Context

If `Specific users` is selected, and a user is selected that's not within the initial list of users, the select box doesn't show the selection.

### Steps to reproduce

- Create a new workflow
- Select `Specific users` in `Who should be notified`
- In the additional box on the right, try searching for a user that is not already populated within the initial list, and select that user

### Expected
- The user is selected and is visible as a selected option within the select input.

### Actual
- The user doesn't show up as selected, unless you search for the same user again, then it'll show as selected, and then disappear again once the search text is cleared.

Reference to support request: https://humanmade.zendesk.com/agent/tickets/5649 & https://humanmade.zendesk.com/agent/tickets/6432

### PR DESCRIPTION
**Pull request by zeshanshani**
To fix issue #161 

### Steps to Reproduce:

1. Add a new workflow.
2. Under "When should the workflow run?" dropdown, select any value.
3. Fill in any subject and message under "What message should be sent?"
4. Set "Specific users..." under "Who should be notified?"
5. In the user selection dropdown, choose a user.
6. Start typing to search for a user. If the dropdown list updates and does not include the previously selected user, that user will disappear from the field.
7. The user will reappear only if the dropdown list again contains the previously selected user.

For more details, watch this video: https://share.cleanshot.com/97dbyHry

---

### Fixes:

1. **Backend (PHP):**
   - The backend now checks if the recipient type is 'user'. If so, it loops through the selected values and returns an array of users with `id` and `name` fields, ensuring previously selected users are preserved in the dropdown.

2. **Frontend (React):**
   - The frontend now initializes the `recipient.users` array with the data coming from PHP for the selected values.
   - The dropdown is always in sync with the latest selected users by using this array.
   - The `onChange` event now appends newly selected users to `recipient.users`, ensuring the list remains up to date and users do not disappear during searches.

### CODE REVIEW

**Comment by goldenapples** [comment]
@roborourke You've got the most context here, can you give this a review? I believe it's addressing the same issue you were tackling in #180.

File: admin/src/WorkflowUI.js [hunk 1]
```diff
@@ -292,7 +292,13 @@ class WorkflowUI extends Component {
 						const recipientValue  = recipient.value
 							? { value: recipientObject.multi ? recipient.value : recipient.value[0] }
 							: {};
-						return Object.assign( {}, recipientObject, recipientValue );
+						let recipientUsers = {};
+
+						if (recipient.users) {
+							recipientUsers = { users: recipientObject.multi ? recipient.users : recipient.users[0] };
+						}
```
Comment (roborourke) [inline admin/src/WorkflowUI.js:299]:
```suggestion
						if ( recipient.users && recipient.users.length > 0 ) {
							recipientUsers = { users: recipientObject.multi ? recipient.users : recipient.users[0] };
						}
```

File: admin/src/WorkflowUI.js [hunk 2]
```diff
@@ -564,21 +570,36 @@ class WorkflowUI extends Component {
 									.then( response => response.json() )
 									.then( data => ({ options: data }) )
 								}
-								value={recipient.value}
+								value={(recipient.users || []).filter(user => recipient.value.includes(String(user.id)))}
```
Comment (roborourke) [inline admin/src/WorkflowUI.js:573]: This doesn't seem to account for `recipient.value` when it isn't an array, eg. if `recipient.multi` is false. Have you confirmed it works in both situations? It's a while since I worked on this, apologies if I'm missing something, but looks llike it can be the case in some situations. 

```suggestion
								value={( recipient.users || [] ).filter( user => recipient.value.includes( String( user.id ) ) )}
```

File: inc/class-rest-workflows-controller.php [hunk 3]
```diff
@@ -85,7 +85,30 @@ public function register_routes() {
...
+
+				// Loop through each recipient and set the 'users' field if field type is 'user'
+				foreach ( $recipients as &$recipient ) {
+					if ( isset( $recipient['id'] ) && $recipient['id'] === 'user' ) {
+						$user_ids = isset( $recipient['value'] ) ? $recipient['value'] : [];
+
+						if ( ! empty( $user_ids ) && is_array( $user_ids ) ) {
+							$users = get_users([
+								'include' => $user_ids
+							]);
```
Comment (roborourke) [inline inc/class-rest-workflows-controller.php:98]:
```suggestion
							$users = get_users( [
								'include' => $user_ids,
							] );
```

File: inc/class-rest-workflows-controller.php [hunk 4]
```diff
@@ -85,7 +85,30 @@ public function register_routes() {
...
+
+							// Prepare the formatted response to include only 'id' and 'name'
+							$recipient['users'] = array_map( function( $user ) {
```
Comment (roborourke) [inline inc/class-rest-workflows-controller.php:101]:
```suggestion
							$recipient['users'] = array_map( function ( $user ) {
```

File: admin/src/WorkflowUI.js (hunk 1 above)
Comment (zeshanshani) [reply admin/src/WorkflowUI.js:299]: @roborourke Good find here

File: admin/src/WorkflowUI.js (hunk 2 above)
Comment (roborourke) [reply admin/src/WorkflowUI.js:573]: @zeshanshani do you have time to resolve this particular issue? Would love to get this merged and released

Comment (zeshanshani) [reply admin/src/WorkflowUI.js:573]: @roborourke I haven't tested that because I could only see that this specific field is always set to multi. Unless I'm wrong here?

Comment (zeshanshani) [reply admin/src/WorkflowUI.js:573]: This is because the condition allows one or more users to select from so the field can never be just one user.

**Comment by zeshanshani** [comment]
@roborourke added the support for single-user selection as well and conducted thorough testing without failure: https://share.cleanshot.com/Qw6fr6p6 (video will self-destruct in 7 days). 

I think it's good to go now unless you notice any issues.

**Review by goldenapples — APPROVED** [review]
Looking good to me. @roborourke Are we good to merge and tag a release?

**Review by roborourke — APPROVED** [review]

**Comment by roborourke** [comment]
@goldenapples yep! Go for it :)
